# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
# IP: The module: 'system_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
# IP: The module: 'system_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/2020_project/ZYNQ_Vitis_7010/23_sd_bmp_hdmi/sd_bmp_hdmi.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
