# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.cache/wt [current_project]
set_property parent.project_path F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/uifdma [current_project]
update_ip_catalog
set_property ip_output_repo f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_hdmi_tx_rtl/asyn_rst_syn.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_color_move/color_720p_timing.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_color_move/color_bar_timing.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_hdmi_tx_rtl/dvi_encoder.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/fdma_contrl.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/fifomem.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_OVsensor.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/helai_async_fifo.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_hdmi_tx_rtl/helai_hdmi_out.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_ov5640_rx/helai_ov5640_rx.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/helai_video_scale.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_ov5640_rx/i2c_ov5640cfg/i2c_dri.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_ov5640_rx/i2c_ov5640cfg/i2c_ov5640_rgb565_cfg.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_ov5640_rx/ov5640_rx.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/ramDualPort.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/ramFifo.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_color_move/rgb_display.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/rptr_empty.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_hdmi_tx_rtl/serializer_10_to_1.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/sync_r2w.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/sync_w2r.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_color_move/video_block_move.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/video_scale.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/video_timing_control.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/async_fifo/wptr_full.v
  F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/new/top.v
}
add_files F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xci
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_ooc.xdc]

read_ip -quiet F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xci
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_ooc.xdc]

read_ip -quiet F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/resize_fifo/resize_fifo.xci
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/resize_fifo/resize_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/resize_fifo/resize_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_video_scale/resize_fifo/resize_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/project_1/project_1.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
