# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xci
# IP: The module: 'w_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xci
# IP: The module: 'w_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Video_scaler/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/w_fifo/w_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
