# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.srcs/sources_1/bd/system/ip/system_Bic_top_0_0/system_Bic_top_0_0.xci
# IP: The module: 'system_Bic_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.gen/sources_1/bd/system/ip/system_Bic_top_0_0/system_Bic_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Bic_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.srcs/sources_1/bd/system/ip/system_Bic_top_0_0/system_Bic_top_0_0.xci
# IP: The module: 'system_Bic_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test8/bmp_hdmi_test8.gen/sources_1/bd/system/ip/system_Bic_top_0_0/system_Bic_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Bic_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
