# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.srcs/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0.xci
# IP: The module: 'system_rst_ps7_0_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.srcs/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0.xci
# IP: The module: 'system_rst_ps7_0_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/bmp_hdmi_test6/bmp_hdmi_test6.gen/sources_1/bd/system/ip/system_rst_ps7_0_150M_0/system_rst_ps7_0_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
