# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xci
# IP: The module: 'r_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xci
# IP: The module: 'r_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/github_project/zyqn/zyqn/V08_Zynq7020_OV5640_Resize_HDMI/helai_ip/helai_fdma_contrl/r_fifo/r_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
