# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/HDMI/bmp_hdmi1113/bmp_hdmi1113.srcs/sources_1/bd/system/ip/system_s02_mmu_0/system_s02_mmu_0.xci
# IP: The module: 'system_s02_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/HDMI/bmp_hdmi1113/bmp_hdmi1113.gen/sources_1/bd/system/ip/system_s02_mmu_0/system_s02_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s02_mmu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/HDMI/bmp_hdmi1113/bmp_hdmi1113.srcs/sources_1/bd/system/ip/system_s02_mmu_0/system_s02_mmu_0.xci
# IP: The module: 'system_s02_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/HDMI/bmp_hdmi1113/bmp_hdmi1113.gen/sources_1/bd/system/ip/system_s02_mmu_0/system_s02_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s02_mmu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
